service: next-level-timing-graphs
app: next-level-timing-graphs

frameworkVersion: ">=3.0.0 <4.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    STAGE: ${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${opt:stage, self:provider.stage}-nlt-results"

functions:
  createResult:
    handler: handlers/poll-results.handle
    timeout: 15
    events:
      - http:
          method: post
          path: results

  getResult:
    handler: handlers/get-race.handle
    events:
      - http:
          method: get
          path: races/{id}

resources:
  Resources:
    ResulsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: '${opt:stage, self:provider.stage}-nlt-results'
        AttributeDefinitions:
          - AttributeName: race
            AttributeType: S
          - AttributeName: sortKey
            AttributeType: S
        KeySchema:
          - AttributeName: race
            KeyType: HASH
          - AttributeName: sortKey
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    ResulsTableV2:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: '${opt:stage, self:provider.stage}-nlt-results-v2'
        AttributeDefinitions:
          - AttributeName: race
            AttributeType: S
          - AttributeName: sortKey
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: raceIndex
            KeySchema:
              - AttributeName: race
                KeyType: HASH
              - AttributeName: sortKey
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
